FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the flask application code
COPY ./flask_app ./flask_app

EXPOSE 5000

# Set environment variables
ENV API_URL=http://api:8000
ENV FLASK_APP=flask_app/app.py

CMD ["python", "flask_app/app.py"]
